services:
  netease-url:
    build:
      context: .
      dockerfile: Dockerfile
    image: netease_url:latest
    container_name: netease-url
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
